#!/bin/sh
set -e
chown -R elasticsearch:elasticsearch /elasticsearch/data
chown -R elasticsearch:elasticsearch /elasticsearch/logs
exec sudo -E -u elasticsearch /elasticsearch/bin/elasticsearch --config=/elasticsearch/config/elasticsearch.yml
